// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// TaskRequest представляет запрос на получение задачи
type TaskRequest struct {
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *TaskRequest) Reset()         {}
func (x *TaskRequest) String() string { return "" }
func (x *TaskRequest) ProtoMessage()  {}

// Task представляет задачу для вычисления
type Task struct {
	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          float64 `protobuf:"fixed64,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64 `protobuf:"fixed64,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string  `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime int32   `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Priority      int32   `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *Task) Reset()         {}
func (x *Task) String() string { return "" }
func (x *Task) ProtoMessage()  {}

// TaskResult представляет результат выполнения задачи
type TaskResult struct {
	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TaskResult) Reset()         {}
func (x *TaskResult) String() string { return "" }
func (x *TaskResult) ProtoMessage()  {}

// TaskResultResponse представляет ответ на результат выполнения задачи
type TaskResultResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *TaskResultResponse) Reset()         {}
func (x *TaskResultResponse) String() string { return "" }
func (x *TaskResultResponse) ProtoMessage()  {}

var File_proto_calculator_proto protoreflect.FileDescriptor
